export type Locale = "ar" | "en";

export const translations = {
  en: {
    // General
    appTitle: "AI Bot Control Hub",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    close: "Close",
    search: "Search...",
    confirm: "Confirm",
    actions: "Actions",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    available: "Available",
    unavailable: "Unavailable",
    pending: "Pending",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    completed: "Completed",
    noData: "No data available",
    createdAt: "Created At",
    name: "Name",
    phone: "Phone",
    address: "Address",
    description: "Description",
    price: "Price",
    image: "Image",
    category: "Category",
    date: "Date",
    notes: "Notes",
    reason: "Reason",
    type: "Type",
    service: "Service",

    // Navigation
    nav: {
      dashboard: "Dashboard",
      channels: "Channels",
      catalog: "Catalog",
      bookings: "Bookings",
      clients: "Clients",
      chat: "Live Chat",
      blacklist: "Blacklist",
    },

    // Dashboard
    dashboard: {
      title: "Dashboard",
      subtitle: "Overview of your AI Bot performance",
      activeChannels: "Active Channels",
      totalMessages: "Total Messages",
      totalBookings: "Total Bookings",
      conversionRate: "Conversion Rate",
      service: "Service",
      recentBookings: "Recent Bookings",
      channelPerformance: "Channel Performance",
      weeklyTrend: "Weekly Trend",
      messagesByChannel: "Messages by Channel",
    },

    // Channels
    channels: {
      title: "Channel Management",
      subtitle: "Connect and configure your communication channels",
      addChannel: "Add Channel",
      editChannel: "Edit Channel",
      channelName: "Channel Name",
      channelType: "Channel Type",
      credentials: "Credentials",
      credentialKey: "Key",
      credentialValue: "Value",
      addCredential: "Add Credential",
      variables: "Variables",
      variableName: "Variable Name",
      variableValue: "Variable Value",
      addVariable: "Add Variable",
      imageSets: "Image Sets",
      imageSetName: "Set Name",
      addImageSet: "Add Image Set",
      addImage: "Add Image",
      imageUrl: "Image URL",
      responseDelay: "Response Delay (seconds)",
      whatsapp: "WhatsApp",
      facebook: "Facebook Messenger",
      instagram: "Instagram Direct",
      connectionStatus: "Connection Status",
      toggleActive: "Toggle Active",
      deleteChannel: "Delete Channel",
      deleteConfirm: "Are you sure you want to delete this channel?",
    },

    // Catalog
    catalog: {
      title: "Product & Service Catalog",
      subtitle: "Manage your products and services that the bot can offer",
      addProduct: "Add Product",
      editProduct: "Edit Product",
      productName: "Product Name",
      productNameAr: "Product Name (Arabic)",
      productDescription: "Description",
      productDescriptionAr: "Description (Arabic)",
      productPrice: "Price",
      productImage: "Image URL",
      productCategory: "Category",
      availability: "Availability",
      deleteProduct: "Delete Product",
      deleteConfirm: "Are you sure you want to delete this product?",
      allCategories: "All Categories",
    },

    // Bookings
    bookings: {
      title: "Bookings & Leads",
      subtitle: "Track all bookings generated by your AI bot",
      clientName: "Client Name",
      clientPhone: "Client Phone",
      clientAddress: "Client Address",
      serviceSummary: "Service Summary",
      channelSource: "Channel Source",
      bookingDate: "Booking Date",
      bookingStatus: "Booking Status",
      allStatuses: "All Statuses",
      allChannels: "All Channels",
      viewDetails: "View Details",
      updateStatus: "Update Status",
    },

    // Clients
    clients: {
      title: "Client Directory",
      subtitle: "Manage your client database",
      addClient: "Add Client",
      editClient: "Edit Client",
      clientName: "Client Name",
      clientPhone: "Client Phone",
      clientAddress: "Client Address",
      clientNotes: "Notes",
      deleteClient: "Delete Client",
      deleteConfirm: "Are you sure you want to delete this client?",
      totalClients: "Total Clients",
    },

    // Blacklist
    blacklist: {
      title: "Blacklist",
      subtitle: "Block numbers and IDs from bot interactions",
      addEntry: "Block New Number/ID",
      identifier: "Phone Number / ID",
      identifierType: "Type",
      blockReason: "Reason for Blocking",
      phoneType: "Phone Number",
      idType: "User ID",
      deleteEntry: "Remove from Blacklist",
      deleteConfirm: "Are you sure you want to remove this entry from the blacklist?",
      totalBlocked: "Total Blocked",
    },

    // Chat
    chat: {
      title: "Live Chat",
      subtitle: "Monitor and simulate bot conversations",
      conversations: "Conversations",
      selectConversation: "Select a conversation",
      typeMessage: "Type a message...",
      send: "Send",
      user: "User",
      bot: "AI Bot",
      agent: "Human Agent",
      newConversation: "New Conversation",
      endConversation: "End Conversation",
      noConversations: "No active conversations",
    },
  },
  ar: {
    // General
    appTitle: "مركز تحكم البوت الذكي",
    loading: "جارٍ التحميل...",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    close: "إغلاق",
    search: "بحث...",
    confirm: "تأكيد",
    actions: "إجراءات",
    status: "الحالة",
    active: "نشط",
    inactive: "غير نشط",
    available: "متاح",
    unavailable: "غير متاح",
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    cancelled: "ملغي",
    completed: "مكتمل",
    noData: "لا توجد بيانات",
    createdAt: "تاريخ الإنشاء",
    name: "الاسم",
    phone: "الهاتف",
    address: "العنوان",
    description: "الوصف",
    price: "السعر",
    image: "الصورة",
    category: "الفئة",
    date: "التاريخ",
    notes: "ملاحظات",
    reason: "السبب",
    type: "النوع",
    service: "الخدمة",

    // Navigation
    nav: {
      dashboard: "لوحة القيادة",
      channels: "القنوات",
      catalog: "الكتالوج",
      bookings: "الحجوزات",
      clients: "العملاء",
      chat: "المحادثات",
      blacklist: "القائمة السوداء",
    },

    // Dashboard
    dashboard: {
      title: "لوحة القيادة",
      subtitle: "نظرة عامة على أداء البوت الذكي",
      activeChannels: "القنوات النشطة",
      totalMessages: "إجمالي الرسائل",
      totalBookings: "إجمالي الحجوزات",
      conversionRate: "نسبة التحويل",
      service: "الخدمة",
      recentBookings: "أحدث الحجوزات",
      channelPerformance: "أداء القنوات",
      weeklyTrend: "الاتجاه الأسبوعي",
      messagesByChannel: "الرسائل حسب القناة",
    },

    // Channels
    channels: {
      title: "إدارة القنوات",
      subtitle: "ربط وإعداد قنوات التواصل",
      addChannel: "إضافة قناة",
      editChannel: "تعديل القناة",
      channelName: "اسم القناة",
      channelType: "نوع القناة",
      credentials: "بيانات الربط",
      credentialKey: "المفتاح",
      credentialValue: "القيمة",
      addCredential: "إضافة بيان",
      variables: "المتغيرات",
      variableName: "اسم المتغير",
      variableValue: "قيمة المتغير",
      addVariable: "إضافة متغير",
      imageSets: "مجموعات الصور",
      imageSetName: "اسم المجموعة",
      addImageSet: "إضافة مجموعة",
      addImage: "إضافة صورة",
      imageUrl: "رابط الصورة",
      responseDelay: "تأخير الرد (بالثواني)",
      whatsapp: "واتساب",
      facebook: "ماسنجر فيسبوك",
      instagram: "انستجرام",
      connectionStatus: "حالة الاتصال",
      toggleActive: "تفعيل/إيقاف",
      deleteChannel: "حذف القناة",
      deleteConfirm: "هل أنت متأكد من حذف هذه القناة؟",
    },

    // Catalog
    catalog: {
      title: "كتالوج المنتجات والخدمات",
      subtitle: "إدارة المنتجات والخدمات التي يقدمها البوت",
      addProduct: "إضافة منتج",
      editProduct: "تعديل المنتج",
      productName: "اسم المنتج",
      productNameAr: "اسم المنتج (عربي)",
      productDescription: "الوصف",
      productDescriptionAr: "الوصف (عربي)",
      productPrice: "السعر",
      productImage: "رابط الصورة",
      productCategory: "الفئة",
      availability: "التوفر",
      deleteProduct: "حذف المنتج",
      deleteConfirm: "هل أنت متأكد من حذف هذا المنتج؟",
      allCategories: "جميع الفئات",
    },

    // Bookings
    bookings: {
      title: "الحجوزات والعملاء المحتملين",
      subtitle: "تتبع جميع الحجوزات الناتجة عن البوت الذكي",
      clientName: "اسم العميل",
      clientPhone: "هاتف العميل",
      clientAddress: "عنوان العميل",
      serviceSummary: "ملخص الخدمة",
      channelSource: "مصدر القناة",
      bookingDate: "تاريخ الحجز",
      bookingStatus: "حالة الحجز",
      allStatuses: "جميع الحالات",
      allChannels: "جميع القنوات",
      viewDetails: "عرض التفاصيل",
      updateStatus: "تحديث الحالة",
    },

    // Clients
    clients: {
      title: "دليل العملاء",
      subtitle: "إدارة قاعدة بيانات العملاء",
      addClient: "إضافة عميل",
      editClient: "تعديل العميل",
      clientName: "اسم العميل",
      clientPhone: "هاتف العميل",
      clientAddress: "عنوان العميل",
      clientNotes: "ملاحظات",
      deleteClient: "حذف العميل",
      deleteConfirm: "هل أنت متأكد من حذف هذا العميل؟",
      totalClients: "إجمالي العملاء",
    },

    // Blacklist
    blacklist: {
      title: "القائمة السوداء",
      subtitle: "حظر الأرقام والمعرفات من تفاعل البوت",
      addEntry: "حظر رقم/معرف جديد",
      identifier: "رقم الهاتف / المعرف",
      identifierType: "النوع",
      blockReason: "سبب الحظر",
      phoneType: "رقم الهاتف",
      idType: "معرف المستخدم",
      deleteEntry: "إزالة من القائمة السوداء",
      deleteConfirm: "هل أنت متأكد من إزالة هذا الإدخال من القائمة السوداء؟",
      totalBlocked: "إجمالي المحظورين",
    },

    // Chat
    chat: {
      title: "المحادثات المباشرة",
      subtitle: "مراقبة ومحاكاة محادثات البوت",
      conversations: "المحادثات",
      selectConversation: "اختر محادثة",
      typeMessage: "اكتب رسالة...",
      send: "إرسال",
      user: "المستخدم",
      bot: "البوت الذكي",
      agent: "العميل البشري",
      newConversation: "محادثة جديدة",
      endConversation: "إنهاء المحادثة",
      noConversations: "لا توجد محادثات نشطة",
    },
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function t(locale: Locale, key: string): string {
  const keys = key.split(".");
  let current: unknown = translations[locale];
  for (const k of keys) {
    if (current && typeof current === "object" && k in current) {
      current = (current as Record<string, unknown>)[k];
    } else {
      return key;
    }
  }
  return typeof current === "string" ? current : key;
}

export function isRTL(locale: Locale): boolean {
  return locale === "ar";
}
